### ISSUE TITLE
Curiosidade sobre o seu terminal

### ISSUE THREAD

**Issue by jonathanbergson** [thalesmello/slides#2]
Cara assisti sua palestra no canal do pagar.me sobre `NeoVim`, achei muito foda.
Mas gostaria de tirar algumas dúvidas sobre o que você usa no seu terminal, acho que você está utilizando o `oh-my-zsh`:

- Qual configuração ou plugin você está usando no `zsh` para deixar os directórios mais curtos? Exemplo: `~/pr/slides`. Cheguei a experimentar o plugin `shrink-path` mas por algum motivo o meu terminal ficou bem zoado. Se você puder mandar a sua configuração, agradeceria bastante.
<img width="214" alt="screen shot 2018-03-12 at 17 29 15" src="https://user-images.githubusercontent.com/6494405/37307837-ec3bc416-261a-11e8-90ba-e2254ab62062.png">

- O que você utiliza para exibir os dados da sua máquina no rodapé do terminal?
<img width="850" alt="screen shot 2018-03-12 at 17 28 58" src="https://user-images.githubusercontent.com/6494405/37307812-dff00668-261a-11e8-9df4-8e8e820af014.png">

**Comment by thalesmello** [comment]
Respondendo às perguntas:

- Uso [fish-shell](https://fishshell.com/) com o tema [bobthefish](https://github.com/oh-my-fish/theme-bobthefish).
- Sobre informações no canto inferior direito, uso tmux com [minha configuração](https://github.com/thalesmello/dotfiles/blob/master/tmux.conf). O layout dos componentes é feito com o plugin [tmuxline](https://github.com/edkolev/tmuxline.vim) do Vim.
