### ISSUE TITLE
O nvim-autocomletions-manager esta morto e agora?

### ISSUE THREAD

**Issue by BruceMustache** [thalesmello/slides#3]
o repo deste plugin foi arquivado 
tentei instalar o nmc2 (que ele indicou)
porem nao funcionou

E agora? Alguem pode me ajudar?

**Comment by thalesmello** [comment]
Olá, Bruce. Realmente os slides da palestra precisam ser atualizados.

Pode dar mais detalhes do que o `ncm2` não funcionou? Eu uso e funciona perfeitamente pra mim. No caso, a diferença é que agora é necessário instalar os plugins individuais.

Você tem o seu Vimrc para eu poder dar uma olhada?

**Comment by BruceMustache** [comment]
Eu instalei o plugin usando o PlugInstall
Mas na hora de usar dava um error relacionado ao buffer
Porem quando fui instalar agora funcionou corretamente
Estou com difculdade agora para instalar os plugins individuais
Queria que meu nvim fosse como o vscode 
Onde voce conseque programar numa linguagem/framework novo sem conhecer direito ele

init.vim:
call plug#begin()
  Plug 'morhetz/gruvbox' "theme
  Plug 'terryma/vim-multiple-cursors' "refactoring
  Plug 'sheerun/vim-polyglot' "arquivos de syntax
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
  Plug 'junegunn/fzf.vim' "search files
  Plug 'ncm2/ncm2'  "auto completions
  Plug 'roxma/nvim-yarp'  "ncm2
  Plug 'ncm2/ncm2-bufword'
  Plug 'ncm2/ncm2-path'
  Plug 'ncm2/ncm2-syntax' | Plug 'Shougo/neco-syntax'
  Plug 'ncm2/ncm2-jedi'
call plug#end()

colorscheme gruvbox
set background=dark

"ncm2
autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect

"jedi
"g:ncm2_jedi#python_version
"g:ncm2_jedi#environment
"g:ncm2_jedi#settings

set hidden "pode editar outro arquivo sem precisar salvar aquele"
set number "visualizar linhas"
set relativenumber "relativas a distancia"
set mouse=a "abilita o mouse"
set inccommand=split

let mapleader="\<space>" "leader key
" n -- normal mode
" nore -- no recursive
" <cr> -- enter key
" <c> -- Ctrl key
nnoremap <leader>; A;<esc>
nnoremap <leader>ev :vsplit ~/.c

onfig/nvim/init.vim<cr>
nnoremap <leader>sv :source ~/.config/nvim/init.vim<cr>

nnoremap <c-p> :Files<cr>
nnoremap <c-f> :Ag 
" <c-f> atalho para busca no projeto

**Comment by BruceMustache** [comment]
@thalesmello achei outro plugin de autocomplete 
chamado YouCompleteMe voce conhece ele? Sera que ele e melhor que o nmc2?

**Comment by thalesmello** [comment]
@BruceMoustache YouCompleteMe é bom. Já usei no passado, mas acho o ncm2 mais simples. Fechando porque o problema foi resolvido.
